name: Deploy

on:
  push:
    branches: [master]

jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "npm install"
      - run: echo "npx serverless deploy --stage staging"

  approve-prod:
    runs-on: ubuntu-latest
    needs: [staging-deploy]
    environment:
      name: production
    steps:
      - run: echo "Waiting for manual approval"

  prod-deploy:
    runs-on: ubuntu-latest
    needs: [approve-prod]
    steps:
      - uses: actions/checkout@v3
      - run: echo "npm install"
      - run: echo "npx serverless deploy --stage production"
